### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by guettli** [ahrtr/etcd-defrag#2]
Hi Benjamin Wang 

Is it already ready for production?

I have seen dirty and unreliable scripts doing the etcd defragmentation, that's why I am very happy to see this tool. Thank you!

**Comment by ahrtr** [comment]
hi Thomas Güttler,

Yes, I think it's almost ready for production. 

I will wait for feedback for a couple of days, then create a tag (e.g. v0.1.0) afterwards.

Please feel free to let me know if you have any suggestions or questions.

I am also thinking how to integrate this tool into production. [K8s cronjob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) may not be feasible, because it's running in data plane (work nodes), but etcd runs in control plane (master nodes), and usually data plane has no access to the control plane.

The good news is that if users already have a script to do it, then they can just replace the script with this tool.

**Comment by ahrtr** [comment]
If we need to integrate this tool into products/platforms (e.g. EKS, AKS, TKG or OpenShift), then I think it should be running in the same plane (e.g. on master) and namespace as etcd.

**Comment by ahrtr** [comment]
@guettli I just released v0.1.0, https://github.com/ahrtr/etcd-defrag/releases/tag/v0.1.0 

Please let me know if you have any questions, comments or suggestions. thx.

**Comment by guettli** [comment]
Thank you very much. Closing this.
